# Generated by Django 6.0.6 on 2026-07-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(blank=True, help_text='Transaction code returned by eSewa', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(blank=True, help_text='Unique transaction ID from eSewa', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('eSewa', 'eSewa')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order Placed', max_length=20),
        ),
    ]
