# Generated by Django 6.0.5 on 2026-06-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('stock_quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('reorder_level', models.IntegerField(default=10)),
            ],
        ),
    ]
