# Generated by Django 6.0.6 on 2026-07-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_hierarchical_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='menuitemrecipe',
            options={'verbose_name': 'Menu Item Recipe', 'verbose_name_plural': 'Menu Item Recipes'},
        ),
    ]
